version: '3'
services:
  web:
    image: php:7.1-alpine
    container_name: unipago-sdk-php
    hostname: unipago-sdk-php
    command: php -S 0.0.0.0:80 -t /app/examples
    working_dir: /app/examples
    ports:
      - 8080:80
    volumes:
      - ./:/app
    environment:
      CLIENT_ID: 'CLIENT_ID'
      CLIENT_SECRET: 'CLIENT_SECRET'

  composer:
    image: composer/composer
    network_mode: host
    command: install --ignore-platform-reqs --prefer-dist -o
    volumes:
      - ./:/app

networks:
  default:
    external:
      name: dev