version: '2'
services:

  web:
    image: php:7.1-alpine
    container_name: dev-unipago-api-sdk-php-web
    hostname: dev-unipago-api-sdk-php-web
    command: php -S 0.0.0.0:80 -t /app/tests
    volumes:
      - ./:/app

  composer:
    image: composer/composer
    network_mode: host
    command: install --ignore-platform-reqs --prefer-dist -o
    volumes:
      - ./:/app

networks:
  default:
    external:
      name: dev